# Generated by Django 5.1.5 on 2026-02-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter (1 borne)'), ('standard', 'Standard (3 bornes)'), ('premium', 'Premium (10 bornes)'), ('enterprise', 'Enterprise (illimité)')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspendue'), ('expired', 'Expirée'), ('revoked', 'Révoquée')], default='active', max_length=20)),
                ('max_terminals', models.IntegerField(default=3)),
                ('features', models.JSONField(blank=True, default=list, help_text="Ex: ['kds', 'analytics', 'multi_language']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='terminal.license')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=64)),
                ('machine_name', models.CharField(blank=True, max_length=200)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='terminal.license')),
            ],
            options={
                'unique_together': {('license', 'machine_id')},
            },
        ),
    ]
