# Generated by Django 5.1.5 on 2026-03-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_employee_address_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
