# Generated by Django 5.1.5 on 2026-04-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_kioskconfig_new_features'),
        ('user', '0005_custom_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('logout_reason', models.CharField(choices=[('manual', 'Déconnexion manuelle'), ('timeout', 'Inactivité (timeout)'), ('forced', 'Déconnexion forcée')], default='manual', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_sessions', to='user.employee')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['employee', 'login_at'], name='user_cashie_employe_01a2ea_idx'), models.Index(fields=['restaurant', 'login_at'], name='user_cashie_restaur_f7ff3c_idx')],
            },
        ),
    ]
