# Generated by Django 5.1.5 on 2026-02-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, help_text="Ex: 'menu', 'group_menu', 'option', 'order', 'step', 'step_option'", max_length=100)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=20)),
                ('record_id', models.IntegerField(blank=True, help_text="ID de l'objet concerné dans sa table d'origine", null=True)),
                ('data', models.JSONField(default=dict, help_text="Snapshot JSON complet de l'objet au moment du changement")),
                ('source', models.CharField(choices=[('server', 'Serveur / Admin'), ('terminal', 'Borne / Terminal')], default='server', max_length=50)),
                ('terminal_uuid', models.CharField(blank=True, help_text='UUID de la borne qui a émis le changement (pour éviter de le lui renvoyer)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['restaurant', 'created_at'], name='sync_synclo_restaur_1de86c_idx'), models.Index(fields=['restaurant', 'table_name', 'created_at'], name='sync_synclo_restaur_dd215e_idx')],
            },
        ),
    ]
