# Generated by Django 5.1.5 on 2026-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_kds_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kds_status',
            field=models.CharField(choices=[('pending_validation', 'En attente de validation'), ('new', 'Nouvelle'), ('in_progress', 'En préparation'), ('done', 'Prête'), ('delivered', 'Livrée')], default='pending_validation', max_length=20),
        ),
    ]
