# Generated by Django 5.1.5 on 2026-03-28 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True)),
                ('sync_type', models.CharField(choices=[('push', 'Push (terminal vers cloud)'), ('pull', 'Pull (cloud vers terminal)'), ('snapshot', 'Snapshot complet'), ('auto_sync', 'Sync automatique')], max_length=20)),
                ('terminal_uuid', models.CharField(blank=True, default='', max_length=255)),
                ('records_count', models.IntegerField(default=0, help_text="Nombre d'enregistrements synchronises")),
                ('errors_count', models.IntegerField(default=0, help_text="Nombre d'erreurs")),
                ('duration_ms', models.IntegerField(default=0, help_text='Duree en millisecondes')),
                ('success', models.BooleanField(default=True)),
                ('error_details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Metrique de synchronisation',
                'verbose_name_plural': 'Metriques de synchronisation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant_id', '-created_at'], name='audit_syncm_restaur_0a461a_idx'), models.Index(fields=['sync_type', '-created_at'], name='audit_syncm_sync_ty_e6836d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(blank=True, default='', help_text="Telephone de l'utilisateur (sauvegarde si le compte est supprime)", max_length=20)),
                ('user_role', models.CharField(blank=True, default='', help_text="Role de l'utilisateur au moment de l'action", max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP du client', null=True)),
                ('action', models.CharField(choices=[('create', 'Creation'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Deconnexion'), ('sync_push', 'Synchronisation Push'), ('sync_pull', 'Synchronisation Pull'), ('export', 'Export de donnees')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='info', max_length=10)),
                ('table_name', models.CharField(blank=True, db_index=True, default='', help_text='Table/modele concerne (ex: menu, order, group_menu)', max_length=100)),
                ('record_id', models.IntegerField(blank=True, help_text="ID de l'objet concerne", null=True)),
                ('record_name', models.CharField(blank=True, default='', help_text="Nom lisible de l'objet (ex: 'Classic Burger')", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text="Description lisible de l'action (ex: 'A modifie le prix de 590 DA a 650 DA')")),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionnaire des champs modifies : {champ: {old: X, new: Y}}')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Donnees supplementaires (endpoint, methode HTTP, etc.)')),
                ('restaurant_id', models.IntegerField(blank=True, db_index=True, help_text='ID du restaurant concerne', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectue l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant_id', '-created_at'], name='audit_audit_restaur_debad3_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['table_name', 'record_id'], name='audit_audit_table_n_dc0494_idx')],
            },
        ),
    ]
