# Generated by Django 4.2.26 on 2025-11-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.FileField(blank=True, null=True, upload_to='restaurant/menugroup/')),
                ('description', models.CharField(max_length=128)),
                ('avalaible', models.BooleanField(default=True)),
                ('extra', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmenus', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solo_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photo', models.FileField(blank=True, null=True, upload_to='restaurant/menu/')),
                ('avalaible', models.BooleanField(default=True)),
                ('extra', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('burger', 'Burger'), ('sandwich', 'Sandwich'), ('wrap', 'Wrap'), ('salad', 'Salad'), ('plate', 'Plate'), ('dessert', 'Dessert'), ('drink', 'Drink')], max_length=20)),
                ('group_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='menu.groupmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.FileField(blank=True, null=True, upload_to='option/photo/')),
                ('type', models.CharField(choices=[('pain', 'Pain'), ('crudité', 'Crudité'), ('accompagnement', 'Accompagnement'), ('sauce', 'Sauce'), ('boisson', 'Boisson'), ('dessert', 'Dessert'), ('base', 'Base'), ('protéine', 'Protéine'), ('salad', 'Salad'), ('plate', 'Plate'), ('drink', 'Drink')], max_length=20)),
                ('avalaible', models.BooleanField(default=True)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('max_options', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('pain', 'Pain'), ('crudité', 'Crudité'), ('accompagnement', 'Accompagnement'), ('sauce', 'Sauce'), ('boisson', 'Boisson'), ('dessert', 'Dessert'), ('base', 'Base'), ('protéine', 'Protéine'), ('salad', 'Salad'), ('plate', 'Plate'), ('drink', 'Drink')], max_length=20)),
                ('avalaible', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='StepOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avalaible', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='menu.option')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepoptions', to='menu.step')),
            ],
            options={
                'unique_together': {('step', 'option')},
            },
        ),
    ]
