# Generated by Django 5.1.5 on 2026-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_groupmenu_position_menu_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='show_for_full',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='step',
            name='show_for_solo',
            field=models.BooleanField(default=True),
        ),
    ]
