# Generated by Django 5.1.5 on 2026-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_step_show_for_full_step_show_for_solo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='show_in_crosssell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('burger', 'Burger'), ('sandwich', 'Sandwich'), ('wrap', 'Wrap'), ('salad', 'Salad'), ('plate', 'Plate'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('individual', 'Article individuel')], max_length=20),
        ),
    ]
