# Generated by Django 5.1.5 on 2026-03-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menu_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Derniere modification'),
        ),
        migrations.AddField(
            model_name='groupmenu',
            name='version',
            field=models.IntegerField(default=1, help_text='Incremente a chaque modification pour detecter les conflits'),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Derniere modification'),
        ),
        migrations.AddField(
            model_name='menu',
            name='version',
            field=models.IntegerField(default=1, help_text='Incremente a chaque modification pour detecter les conflits'),
        ),
        migrations.AddField(
            model_name='option',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='option',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
