# Generated by Django 5.1.5 on 2026-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_groupmenu_updated_at_groupmenu_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='promo_display',
            field=models.CharField(blank=True, choices=[('strikethrough', 'Prix barré + nouveau prix'), ('badge', 'Badge -X% sur la carte'), ('banner', "Bandeau PROMO sur l'image"), ('duo', 'Ancien / Nouveau côte à côte'), ('minimal', 'Prix promo seul (discret)')], default='strikethrough', help_text="Type d'affichage de la promotion", max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='promo_percentage',
            field=models.IntegerField(blank=True, help_text='Réduction en pourcentage (ex: 20 pour -20%). Ignoré si promo_price est défini.', null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix promotionnel fixe (prioritaire sur le pourcentage)', max_digits=10, null=True),
        ),
    ]
