# Generated by Django 5.1.5 on 2026-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menu_promo_display_menu_promo_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='skip_kds',
            field=models.BooleanField(default=False, help_text="Ne pas envoyer cet article à l'écran cuisine (KDS). Ex : boissons, articles sans préparation."),
        ),
    ]
