# Generated by Django 5.1.5 on 2025-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmenu',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
