# Generated by Django 5.1.5 on 2026-03-07 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0056b3', max_length=7)),
                ('secondary_color', models.CharField(default='#ff69b4', max_length=7)),
                ('sidebar_color', models.CharField(default='#1e293b', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='kiosk/logos/')),
                ('screensaver_video', models.FileField(blank=True, null=True, upload_to='kiosk/videos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_config', to='restaurant.restaurant')),
            ],
        ),
    ]
