# Generated by Django 5.1.5 on 2026-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_kioskconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskconfig',
            name='background_color',
            field=models.CharField(default='#F8F9FA', max_length=7),
        ),
        migrations.AddField(
            model_name='kioskconfig',
            name='card_bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='kioskconfig',
            name='category_text_color',
            field=models.CharField(default='#94a3b8', max_length=7),
        ),
        migrations.AddField(
            model_name='kioskconfig',
            name='text_color',
            field=models.CharField(default='#1e293b', max_length=7),
        ),
    ]
