# Generated by Django 5.1.5 on 2026-03-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_kioskconfig_full_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskconfig',
            name='category_bg_color',
            field=models.CharField(default='#1e293b', max_length=7),
        ),
        migrations.AddField(
            model_name='kioskconfig',
            name='selected_category_bg_color',
            field=models.CharField(default='#334155', max_length=7),
        ),
    ]
