# Generated by Django 5.1.5 on 2026-03-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_kioskconfig_composition_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskconfig",
            name="logo_remote_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kioskconfig",
            name="screensaver_video_remote_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
