# Generated by Django 5.1.5 on 2026-03-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_kioskconfig_screensaver_image_remote_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskconfig',
            name='loyalty_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kioskconfig',
            name='loyalty_points_rate',
            field=models.IntegerField(default=10),
        ),
    ]
