# Generated by Django 5.1.5 on 2026-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_kioskconfig_new_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskconfig',
            name='show_inline_cart',
            field=models.BooleanField(default=False, help_text='Afficher le panier en bas de la page menu (sans naviguer vers la page panier)'),
        ),
        migrations.AddField(
            model_name='kioskconfig',
            name='show_refresh_button',
            field=models.BooleanField(default=False, help_text='Afficher un bouton de rafraîchissement du menu sur la borne'),
        ),
    ]
