"""
Django settings for born_dz project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import datetime
from corsheaders.defaults import default_headers
from decouple import config, Csv
import dj_database_url
"""import ssl
import requests

ssl._create_default_https_context = ssl._create_unverified_context
requests.get("https://example.com", verify=False)"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-y($ou%*05+_g)zspa#n-tol!)2p*l_6zr#@(kgomt1hv4$60eu')

DEBUG = config('DEBUG', default=False, cast=bool)

# URL publique du serveur en ligne (utilisée pour les URLs de photos dans la sync)
SERVER_BASE_URL = config('SERVER_BASE_URL', default='https://borndz-production.up.railway.app')

# URL GitHub Release pour le téléchargement du logiciel POS Windows
# Format attendu : https://github.com/<user>/<repo>/releases/download/<tag>/ClickGo-POS-Setup.exe
GITHUB_RELEASE_POS_URL = config('GITHUB_RELEASE_POS_URL', default='')

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.1.50",
    "192.168.1.123",
    "menugo-dz.com",
    "www.menugo-dz.com",
    "borndz-production.up.railway.app",
    "clickgo-interactive.com",
    "www.clickgo-interactive.com",
] + config('ALLOWED_HOSTS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [ #Add created app here like customer, kds...
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "customer",
    "restaurant",
    "KDS",#Kitchen Display Screen
    "POS",#Point Of Sell
    "terminal",
    "order",
    "website",
    "rest_framework",
    'rest_framework_simplejwt',
    "chain",
    "menu",
    "user.apps.UserConfig",
    "manager",
    'corsheaders',#pour pouvoir recevoir des requetes (pas sur),
    "channels", #pour les websockets,
    "borne_sync",
    'sync',
]
# Configuration Channels — Redis en prod, InMemory en local
_REDIS_URL = config('REDIS_URL', default='')
if _REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {"hosts": [_REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
ASGI_APPLICATION = 'born_dz.asgi.application'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Authentification par token JWT
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',  # Seul un utilisateur authentifié peut accéder aux API
    # ],
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=1),  # Change ici la durée du token access
    #"REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=7),  # Change ici la durée du refresh token
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',# pour recevoir des requetes
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',#Pour debug a false et lancer : pip install whitenoise plus gerer les static files comme en bas
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.common.BrokenLinkEmailsMiddleware',  # Ligne à ajouter pour recevoir un mail lorsque la page error servor s'affiche à un utilisateur
]

ROOT_URLCONF = "born_dz.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,"templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "born_dz.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



# Base de données — PostgreSQL si DATABASE_URL défini, SQLite sinon (dev local)
_DATABASE_URL = config('DATABASE_URL', default='')
if _DATABASE_URL:
    DATABASES = {'default': dj_database_url.parse(_DATABASE_URL, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Algiers"

USE_I18N = True

# USE_TZ = False est défini plus bas (timezone naive, Algiers)




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


MEDIA_URL = "/media/" #pour local
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = "static/"



STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] #pour collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
"""
if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
"""
USE_TZ = False
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



AUTH_USER_MODEL = 'user.User' #Specify the user model to use


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.hostinger.com')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='no-reply@menugo-dz.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = False

BASE_URL = config('BASE_URL', default='http://localhost:8000')

# Mode démo : pointe automatiquement sur le restaurant "ClickGo Démo"
# Mettre DEMO_MODE=True dans .env pour activer
DEMO_MODE = config('DEMO_MODE', default=False, cast=bool)


CORS_ALLOW_ALL_ORIGINS = True  # pour tests, à restreindre en prod
CORS_ALLOW_HEADERS = list(default_headers) + [
    'username',
    'password',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://127.0.0.1:8082",
    "http://localhost:8080",
    "http://127.0.0.1:60457",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://localhost:8082",
    "http://localhost:5173",
    "http://menugo-dz.com",
    "http://www.menugo-dz.com",
    "https://borndz-production.up.railway.app",
    "http://192.168.1.50:8000",
    "https://clickgo-siteweb-production.up.railway.app",
    "https://clickgo-interactive.com",
    "https://www.clickgo-interactive.com",
    "https://pos-clickgo.vercel.app",
    "https://borne-clickgo.vercel.app",
] + [f"https://{d}" for d in config('CORS_EXTRA_ORIGINS', default='', cast=Csv()) if d]

CSRF_TRUSTED_ORIGINS = [
    "https://borndz-production.up.railway.app",
]