"""
Django settings for born_dz project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import datetime
from corsheaders.defaults import default_headers
"""import ssl
import requests

ssl._create_default_https_context = ssl._create_unverified_context
requests.get("https://example.com", verify=False)"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y($ou%*05+_g)zspa#n-tol!)2p*l_6zr#@(kgomt1hv4$60eu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS =["127.0.0.1:60457","192.168.1.50","menugo-dz.com", "www.menugo-dz.com","127.0.0.1","localhost","borndz-production.up.railway.app","192.168.1.123"]


# Application definition

INSTALLED_APPS = [ #Add created app here like customer, kds...
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "customer",
    "restaurant",
    "KDS",#Kitchen Display Screen
    "POS",#Point Of Sell
    "terminal",
    "order",
    "website",
    "rest_framework",
    'rest_framework_simplejwt',
    "chain",
    "menu",
    "user.apps.UserConfig",
    "manager",
    'corsheaders',#pour pouvoir recevoir des requetes (pas sur),
    "channels", #pour les websockets,
    "borne_sync",
    'sync',
]
# Configuration Channels
# NOTE: Remplacez par un broker Redis pour la production !
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer' # Simple pour le dev
        # 'BACKEND': 'channels_redis.pubsub.RedisChannelLayer', # Mieux pour la prod
        # 'CONFIG': {"hosts": [('127.0.0.1', 6379)],},
    },
}
ASGI_APPLICATION = 'born_dz.asgi.application'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Authentification par token JWT
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',  # Seul un utilisateur authentifié peut accéder aux API
    # ],
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=1),  # Change ici la durée du token access
    #"REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=7),  # Change ici la durée du refresh token
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',# pour recevoir des requetes
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',#Pour debug a false et lancer : pip install whitenoise plus gerer les static files comme en bas
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.common.BrokenLinkEmailsMiddleware',  # Ligne à ajouter pour recevoir un mail lorsque la page error servor s'affiche à un utilisateur
]

ROOT_URLCONF = "born_dz.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,"templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "born_dz.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
#Connected to postgrSQL DB hosted in RailwayApp
"""
DATABASES = { 
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'PEVppBaRfefiFjYUyQQSxubXJMPuUISP',
        'HOST': 'autorack.proxy.rlwy.net',
        'PORT': '49671',
    }
}
"""
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Algiers"

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


MEDIA_URL = "/media/" #pour local
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = "static/"



STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] #pour collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
"""
if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
"""
USE_TZ = False
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



AUTH_USER_MODEL = 'user.User' #Specify the user model to use


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'no-reply@menugo-dz.com'
EMAIL_HOST_PASSWORD = '05042003H.l@'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False 



BASE_URL = "http://menugo-dz.com"


CORS_ALLOW_ALL_ORIGINS = True  # pour tests, à restreindre en prod
CORS_ALLOW_HEADERS = list(default_headers) + [
    'username',
    'password',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://127.0.0.1:8082",
    "http://localhost:8080",
    "http://127.0.0.1:60457",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://localhost:8081",
    "http://localhost:8082",
    "http://localhost:5173",
    "http://menugo-dz.com",
    "http://www.menugo-dz.com",
    "https://borndz-production.up.railway.app",
    "http://192.168.1.50:8000"

]

