# Generated by Django 5.1.5 on 2026-03-28 12:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0008_groupmenu_updated_at_groupmenu_version_and_more'),
        ('restaurant', '0012_kioskconfig_new_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Boissons, Viandes, Sauces', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('position', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_categories', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Categorie de stock',
                'verbose_name_plural': 'Categories de stock',
                'ordering': ['position', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Coca-Cola 33cl, Steak hache 150g', max_length=200)),
                ('sku', models.CharField(blank=True, default='', help_text='Code article / reference fournisseur (optionnel)', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantite actuelle en stock', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('canette', 'Canette'), ('bouteille', 'Bouteille'), ('portion', 'Portion'), ('gramme', 'Gramme (g)'), ('kilogramme', 'Kilogramme (kg)'), ('litre', 'Litre (L)'), ('centilitre', 'Centilitre (cL)'), ('tranche', 'Tranche'), ('sachet', 'Sachet'), ('carton', 'Carton')], default='piece', help_text='Unite de mesure', max_length=20)),
                ('weight_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Poids/volume par unite (en grammes ou mL). Ex: 150 pour un steak de 150g', max_digits=8)),
                ('min_threshold', models.DecimalField(decimal_places=2, default=10, help_text="Seuil minimum : alerte 'stock bas' quand la quantite descend en dessous", max_digits=10)),
                ('critical_threshold', models.DecimalField(decimal_places=2, default=3, help_text="Seuil critique : alerte 'rupture imminente'. Peut desactiver l'article sur la borne", max_digits=10)),
                ('auto_disable', models.BooleanField(default=True, help_text="Desactiver automatiquement l'article sur la borne quand le stock critique est atteint")),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat unitaire (DA)", max_digits=10)),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('supplier_ref', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.stockcategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Article de stock',
                'verbose_name_plural': 'Articles de stock',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'Stock bas'), ('critical', 'Stock critique'), ('out', 'Rupture de stock')], max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Alerte de stock',
                'verbose_name_plural': 'Alertes de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionStockLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, default=1, help_text="Quantite consommee par utilisation de l'option", max_digits=8)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_links', to='menu.option')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_links', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Lien option-stock',
                'verbose_name_plural': 'Liens option-stock',
            },
        ),
        migrations.CreateModel(
            name='MenuStockLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, default=1, help_text="Quantite d'ingredient consommee par portion vendue. Ex: 1 canette, 150 grammes", max_digits=8)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_links', to='menu.menu')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_links', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Lien menu-stock',
                'verbose_name_plural': 'Liens menu-stock',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entree (reception fournisseur)'), ('out', 'Sortie (commande client)'), ('adjustment', 'Ajustement (inventaire)'), ('waste', 'Perte / dechet'), ('return', 'Retour fournisseur'), ('transfer', 'Transfert inter-restaurant')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantite mouvementee (positive=entree, negative=sortie)', max_digits=10)),
                ('quantity_before', models.DecimalField(decimal_places=2, help_text='Stock avant le mouvement', max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, help_text='Stock apres le mouvement', max_digits=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('order_id', models.IntegerField(blank=True, help_text='ID de la commande qui a declenche la sortie (si applicable)', null=True)),
                ('user_phone', models.CharField(blank=True, default='', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cout unitaire au moment du mouvement', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['restaurant', 'is_active'], name='stock_stock_restaur_fd4abf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['restaurant', 'category'], name='stock_stock_restaur_fce784_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='optionstocklink',
            unique_together={('option', 'stock_item')},
        ),
        migrations.AlterUniqueTogether(
            name='menustocklink',
            unique_together={('menu', 'stock_item')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='stock_stock_stock_i_92c14d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='stock_stock_movemen_cbf66e_idx'),
        ),
    ]
